services:
  - type: web
    name: meu-app-tts
    env: node
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y espeak
      npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: "10000"
